# Generated by Django 5.2.7 on 2025-10-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True),
        ),
    ]
