# Generated by Django 5.2.7 on 2025-10-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_company_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='comany_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
