# Generated by Django 5.2.7 on 2025-10-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_remove_job_company_job_comany_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='curriculum_vitae',
            field=models.FileField(upload_to='cv'),
        ),
    ]
