# Generated by Django 5.2.7 on 2025-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_alter_jobapplication_curriculum_vitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
