# Generated by Django 5.2.7 on 2025-10-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_jobapplication_curriculum_vitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, choices=[('Full_time', 'Full Time'), ('Part_time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=50),
        ),
    ]
