# Generated by Django 5.2.7 on 2025-10-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_alter_job_job_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=50),
        ),
    ]
